<a href="https://colab.research.google.com/github/munmoom/second_semester/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
data1 = [6, 7.5, 9, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 9. , 0. , 1. ])

In [4]:
data2 = [[1,2,3,4], [5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
arr2.shape

(2, 4)

In [6]:
arr2.dtype

dtype('int64')

In [7]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [8]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [9]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [11]:
arr2 > arr

ValueError: ignored

In [ ]:
arr > 3

In [12]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [14]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [15]:
arr_slice[1] = 45
arr

array([ 0,  1,  2,  3,  4, 12, 45, 12,  8,  9])

In [16]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[2]

array([7, 8, 9])

In [17]:
arr2d[0][2]

3

In [18]:
arr2d[0,2]

3

In [27]:
arr = np.arange(9)
arr = arr.reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
arr[:2,1:]

array([[1, 2],
       [4, 5]])

In [29]:
arr[2]

array([6, 7, 8])

In [30]:
arr[:,:2]

array([[0, 1],
       [3, 4],
       [6, 7]])

In [26]:
arr[1,:2]

array([3, 4])

In [31]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])  #shape는 (2,2,3)입니다.
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [32]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
arr3d[0,0]

array([1, 2, 3])

In [35]:
arr3d[0,0,0]

1

In [37]:
arr3d[:,1]

array([[ 4,  5,  6],
       [10, 11, 12]])

In [38]:
arr3d[:,:,2]

array([[ 3,  6],
       [ 9, 12]])