<a href="https://colab.research.google.com/github/munmoom/second_semester/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy
ndarry객체를 제공한다.
* n차원의 homogeneous한 데이터 타입들의 배열, 모든 ele은 같은 type이어야 한다.
*  스칼라값 계산과 비슷한 계산
* shape: 각 차원의 크기
* dtype: arry의 data type




In [2]:
import numpy as np  #import해야 한다

In [3]:
data1 = [6, 7.5, 9, 0, 1]
arr1 = np.array(data1)   #배열 만들기
arr1

array([6. , 7.5, 9. , 0. , 1. ])

In [4]:
data2 = [[1,2,3,4], [5,6,7,8]]
arr2 = np.array(data2)  #이차원배열
print(arr2)
print(type(arr2))   #ndarry

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>


In [ ]:
arr2.shape

(2, 4)

In [5]:
arr2.dtype

dtype('int64')

In [ ]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [6]:
np.zeros((3,6))   # shape(3,6)을 가지는, 0.으로만 구성된 ndarray 만들기

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [7]:
np.arange(5)  # 0부터 4까지의 원소들을 가지는, arange(5)

array([0, 1, 2, 3, 4])

In [17]:
data = np.random.rand(2,3)  # 랜덤하게 random.rand(), zeros와는 다르게 숫자를 바로 넣음
data

array([[0.56779926, 0.12764955, 0.33828216],
       [0.24887334, 0.88928214, 0.26194569]])

In [18]:
data.dtype

dtype('float64')

In [19]:
data.shape

(2, 3)

## 연산

별도의 loop없이도 묶음 계산이 가능, vectorization

같은 크기(equal size)의 array끼리만 계산가능

In [24]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [25]:
arr*arr  #곱하기

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [26]:
arr-arr  #빼기

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
1/arr  #나누기

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [28]:
arr2 > arr  # 둘의 size가 다르다

ValueError: ignored

In [29]:
arr > 3  #상수넣으면 하나씩 비교한다

array([[False, False, False],
       [ True,  True,  True]])

In [32]:
arr==arr  #비교는 Boolean array를 반환한다

array([[ True,  True,  True],
       [ True,  True,  True]])

In [33]:
arr2 = np.array([[2,3,4],[4,5,6]])

In [36]:
arr2 > arr

array([[ True,  True,  True],
       [False, False, False]])

## indexing과 slicing

### array slices, 슬라이싱 한 건 그저 보이는 것일 뿐이다, view일 뿐!

In [38]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
arr[5:8] = 12   #마지막은 포함되지 않는다, 슬라이싱 교체
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [40]:
arr_slice = arr[5:8]  #마지막은 포함되지 않는다
arr_slice

array([12, 12, 12])

In [43]:
arr_slice[1] = 45   # 슬라이싱한 걸 바꿨는데 본 ndarray의 원소도 바뀜
                    # 슬라이싱은 view일 뿐이다!
arr

array([ 0,  1,  2,  3,  4, 12, 45, 12,  8,  9])

In [45]:
ar = arr[5:8].copy()
print(ar)

[12 45 12]


In [49]:
ar[1]=0   #copy()로 따온 것
print(ar)   #수정되었다
print(arr)  #수정되지 않았다
print(type(ar))
print(type(arr))

[12  0 12]
[ 0  1  2  3  4 12 45 12  8  9]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


## 다차원 배열의 indexing과 slicing


In [42]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[2]

array([7, 8, 9])

In [ ]:
arr2d[0][2]  #따로 []쳐서 보거나

3

In [ ]:
arr2d[0,2]  # ','찍어서 보거나 같다

3

In [52]:
arr3d = np.arange(9)
arr3d = arr3d.reshape(3,3)   #reshape하면 shape조정해준다
arr3d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [57]:
arr3d[:2,1:]  #0,1번째 것과 그 안에서 1,2번째 것

array([[1, 2],
       [4, 5]])

In [58]:
arr3d[2]  #두번째 것

array([6, 7, 8])

In [59]:
arr3d[:,:2]  #전체와 그 안에서 0, 1번째 것

array([[0, 1],
       [3, 4],
       [6, 7]])

In [60]:
arr3d[1,:2]  #1번과 그 안에서 0,1번째 것

array([3, 4])

In [62]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])  #shape는 (2,2,3)입니다.
print(arr3d)
print(arr3d.shape)  #바깥쪽부터 센다

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


In [69]:
print(arr3d[0])
#print(type(arr3d[0]))
print(arr3d[0].shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [ ]:
arr3d[0,0]

array([1, 2, 3])

In [71]:
arr3d[0,0,0]
#print(type(arr3d[0,0,0]))

1

In [ ]:
arr3d[:,1]  #전체 안에서 1번째 것들

array([[ 4,  5,  6],
       [10, 11, 12]])

In [72]:
arr3d[:,:,2]  #안, 안에서 2번째 것들(2차원 배열로 나옴)

array([[ 3,  6],
       [ 9, 12]])

## Boolean indexing

In [75]:
names = np.array(['bob', 'joe','bob'])
data = np.random.rand(3,4)
data

array([[0.63737529, 0.85800818, 0.9092463 , 0.51076795],
       [0.88003983, 0.18545995, 0.29556703, 0.06858983],
       [0.25608252, 0.18610683, 0.21738375, 0.27951281]])

In [76]:
names == 'bob'

array([ True, False,  True])

In [79]:
names.dtype

dtype('<U3')

In [80]:
data[names=='bob']  #0번째랑 2번째 것들이 나온다

array([[0.63737529, 0.85800818, 0.9092463 , 0.51076795],
       [0.25608252, 0.18610683, 0.21738375, 0.27951281]])

In [81]:
data[data<0.2] = 0
data

array([[0.63737529, 0.85800818, 0.9092463 , 0.51076795],
       [0.88003983, 0.        , 0.29556703, 0.        ],
       [0.25608252, 0.        , 0.21738375, 0.27951281]])

## Transpose and Reshape

In [88]:
import numpy as np
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [89]:
arr.T  #transpose함

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [91]:
arr   #본래배열은 변하지 않음

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [92]:
arr.transpose((1,0))

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

## 연산

In [82]:
import numpy as np
 
a = np.arange(9).reshape(3,3)
print(a)
print(a.sum(axis=0))  #0축에 있는 것들끼리 더한다. 세로방향.

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[ 9 12 15]


In [ ]:
import numpy as np
 
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
output = arr > 7   #boolean array나온다
print(output)

[[False False False False False]
 [False False  True  True  True]]


In [ ]:
import numpy as np
 
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[:2,2:])   #슬라이싱할 때 마지막거 포함안됨

[[3]
 [6]]


In [ ]:
import numpy as np
 
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a.shape)


(3, 4)


In [ ]:
import numpy as np
 
a = np.array([[1,1,1],[2,2,2],[3,3,3]])
print(a*a)

[[1 1 1]
 [4 4 4]
 [9 9 9]]


In [93]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1] = -1   #홀수를 -1로 만들어버림
arr


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [94]:
Z = np.zeros((3,3),dtype=int)
print(Z)
Z[1:2,::2] = 1
print(Z)
Z[::2,1::2] = 1
print(Z)
np.sum(Z)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 0]
 [1 0 1]
 [0 0 0]]
[[0 1 0]
 [1 0 1]
 [0 1 0]]


4

## 다양한 함수들

In [104]:
arr = np.arange(10).reshape((3.3))
arr

TypeError: ignored

In [97]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [99]:
arr   # 수정안됨

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
np.exp(arr)  #e의 지수로

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [100]:
arr.mean()

4.5

In [102]:
np.mean(arr)

4.5

In [101]:
arr.sum()

45

In [105]:
arr = np.arange(10).reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [106]:
arr.sum(axis=0)

array([ 5,  7,  9, 11, 13])

In [107]:
arr.sum(axis=1)

array([10, 35])

In [108]:
arr.mean(axis=0)

array([2.5, 3.5, 4.5, 5.5, 6.5])

In [109]:
arr.mean(axis=1)

array([2., 7.])

In [110]:
arr.mean()

4.5

In [111]:
import numpy as np
x = np.arange(12).reshape(4,3)
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [112]:
np.mean(x, axis=0)

array([4.5, 5.5, 6.5])

In [113]:
x = x-np.mean(x,axis=0)
x

array([[-4.5, -4.5, -4.5],
       [-1.5, -1.5, -1.5],
       [ 1.5,  1.5,  1.5],
       [ 4.5,  4.5,  4.5]])

### 선형대수랑 난수배열생성도 있음

## 퀴즈

In [114]:
import numpy as np
a=np.arange(9).reshape(3,3)
print(a.sum(axis=0))

[ 9 12 15]


In [115]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# 실습

In [ ]:
numpy를 import 하시오
import ~~~
import numpy as np
### Exercise 1
10부터 19까지 범위를 가지는 numpy array생성하라.  
(Hint) np.arange
​
array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])
np.arange(10,20)
array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])
### Exercise 2
- (2-1) 0부터 11까지의 (4,3) array를 arange와 reshape를 이용해서 만들고  
- (2-2) 첫번째 열과 세번째 열의 값을 slicing을 통해서 가져오라.  
array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])
       
array([[ 0,  2],
       [ 3,  5],
       [ 6,  8],
       [ 9, 11]])
arr = np.arange(0,12).reshape((4,3))
arr
array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])
arr[:,0:3:2]
array([[ 0,  2],
       [ 3,  5],
       [ 6,  8],
       [ 9, 11]])
### Exercise 3
array([[1, 2],[3, 4]]) 2차원 배열을 생성하고  
배열의 모든 원소에 대해서 주어진 함수  f(x)=x^2+x−6 을 적용해 보자.
array([[1, 2],
       [3, 4]])
​
array([[-4,  0],
       [ 6, 14]])
arr2d = np.arange(1,5).reshape((2,2))
#arr2d = np.array([[1,2],[3,4]])
arr2d
array([[1, 2],
       [3, 4]])
arr2d*arr2d + arr2d - 6
array([[-4,  0],
       [ 6, 14]])
### Exercise 4
- (3-1) 1부터 11까지 5행, 2열의 array를 만들어라  
- (3-2) 만든 array에서 모든요소의합, 각 열의 합, 각 행의 합을 계산해보자
(Hint) data.sum()
array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])
       
전체합: 55
열의합: array([25, 30])
행의합: array([ 3,  7, 11, 15, 19])
arr = np.arange(1,11).reshape((5,2))
arr
array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])
arr.sum()
55
arr.sum(axis=0)
array([25, 30])
arr.sum(axis=1)
array([ 3,  7, 11, 15, 19])
### Exercise 5
- (4-1) array([[ 2,  4,  6],[ 8, 10, 12]]) 를 만든다.  
- (4-2) 해당 array를 이용하여 전체 평균 및 표준 편차를 구하고, Z 정규화해보자   
$$ Z =  \frac{ X - \mu}{ \sigma} $$  
(Hint) np.mean(), np.std()
array([[ 2,  4,  6],
       [ 8, 10, 12]])
​
평균: 7.0
표준편차: 3.415650255319866
Z transform 결과
array([[-1.46385011, -0.87831007, -0.29277002],
       [ 0.29277002,  0.87831007,  1.46385011]])
arr2d = np.arange(2,13,2).reshape((2,3))
#arr2d = np.array([[2,4,6],[8,10,12]])
arr2d
array([[ 2,  4,  6],
       [ 8, 10, 12]])
m = arr2d.mean()
s = arr2d.std()
Z = (arr2d - m)/s
Z
array([[-1.46385011, -0.87831007, -0.29277002],
       [ 0.29277002,  0.87831007,  1.46385011]])
### Exercise 6
(5,5) 행렬을 만들어 체스 보드 패턴으로 채워보자
[0, 1, 0, 1, 0],  
[1, 0, 1, 0, 1],  
[0, 1, 0, 1, 0],  
[1, 0, 1, 0, 1],  
[0, 1, 0, 1, 0]]
arr = np.zeros((5,5))
arr
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])
arr[0,1::2]=1
arr[1,::2]=1
arr[2,1::2]=1
arr[3,::2]=1
arr[4,1::2]=1
​
arr
array([[0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.]])
arr[::2,1:2]=1
arr[1::2,::2]=1
​
arr
array([[0., 1., 0., 0., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 0., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 0., 0.]])
arr = np.arange(25).reshape(5,5)
arr
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])
arr[arr%2 == 0] = 0
arr[arr%2 == 1] = 1
​
arr
array([[0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0]])
### Exercise 7
주어진 두 array의 내적을 numpy를 이용하여 작성하시오.
array([4, 5])
array([4, 5])
벡터의 내적 : 78
arr = np.array([4, 5])
arr
array([4, 5])
np.dot(arr,arr)
41